name: matoon
version: 0.0.0
publish_to: none

# ============================================================

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  bloc: any

  register:
    path: ../layers/register
  common:
    path: ../libraries/common

dev_dependencies:
  flutter_lints: ^5.0.0

# ============================================================

flutter:
  uses-material-design: true
  assets:
    - assets/fakes/
    - assets/images/
    - assets/translates/